<!doctype html>
<html lang="en"><head><meta charSet="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>Mochawesome Report</title><link rel="stylesheet" href="assets/app.css"/></head><body data-raw="{&quot;stats&quot;:{&quot;suites&quot;:2,&quot;tests&quot;:6,&quot;passes&quot;:1,&quot;pending&quot;:0,&quot;failures&quot;:5,&quot;start&quot;:&quot;2020-06-25T23:01:57.757Z&quot;,&quot;end&quot;:&quot;2020-06-25T23:01:57.757Z&quot;,&quot;duration&quot;:2468,&quot;testsRegistered&quot;:6,&quot;passPercent&quot;:16.666666666666668,&quot;pendingPercent&quot;:0,&quot;other&quot;:0,&quot;hasOther&quot;:false,&quot;skipped&quot;:0,&quot;hasSkipped&quot;:false},&quot;results&quot;:[{&quot;uuid&quot;:&quot;144992f1-9ec8-4fa3-b6e8-08b0600a1705&quot;,&quot;title&quot;:&quot;&quot;,&quot;fullFile&quot;:&quot;&quot;,&quot;file&quot;:&quot;&quot;,&quot;beforeHooks&quot;:[],&quot;afterHooks&quot;:[],&quot;tests&quot;:[],&quot;suites&quot;:[{&quot;uuid&quot;:&quot;b503848c-31a5-4415-b5ce-83f0d4f61ba2&quot;,&quot;title&quot;:&quot;API Testing with Cypress&quot;,&quot;fullFile&quot;:&quot;&quot;,&quot;file&quot;:&quot;&quot;,&quot;beforeHooks&quot;:[],&quot;afterHooks&quot;:[],&quot;tests&quot;:[{&quot;title&quot;:&quot;Validate the header&quot;,&quot;fullTitle&quot;:&quot;API Testing with Cypress Validate the header&quot;,&quot;timedOut&quot;:null,&quot;duration&quot;:766,&quot;state&quot;:&quot;failed&quot;,&quot;speed&quot;:null,&quot;pass&quot;:false,&quot;fail&quot;:true,&quot;pending&quot;:false,&quot;context&quot;:null,&quot;code&quot;:&quot;result = cy.request(&#x27;http://services.groupkt.com/country/get/iso2code/AU&#x27;);\nresult.its(&#x27;headers&#x27;).its(&#x27;content-type&#x27;).should(&#x27;include&#x27;, &#x27;application/json&#x27;);&quot;,&quot;err&quot;:{&quot;message&quot;:&quot;CypressError: cy.request() failed trying to load:\n\nhttp://services.groupkt.com/country/get/iso2code/AU\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: getaddrinfo ENOTFOUND services.groupkt.com services.groupkt.com:80\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: http://services.groupkt.com/country/get/iso2code/AU\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: getaddrinfo ENOTFOUND services.groupkt.com services.groupkt.com:80\n    at new RequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:185:22)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at Request.onRequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:881:8)\n    at emitOne (events.js:120:20)\n    at ClientRequest.emit (events.js:210:7)\n    at Socket.socketErrorListener (_http_client.js:401:9)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n&quot;,&quot;estack&quot;:&quot;CypressError: cy.request() failed trying to load:\n\nhttp://services.groupkt.com/country/get/iso2code/AU\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: getaddrinfo ENOTFOUND services.groupkt.com services.groupkt.com:80\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: http://services.groupkt.com/country/get/iso2code/AU\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: getaddrinfo ENOTFOUND services.groupkt.com services.groupkt.com:80\n    at new RequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:185:22)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at Request.onRequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:881:8)\n    at emitOne (events.js:120:20)\n    at ClientRequest.emit (events.js:210:7)\n    at Socket.socketErrorListener (_http_client.js:401:9)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n\n    at Object.cypressErr (http://localhost:52498/__cypress/runner/cypress_runner.js:65727:11)\n    at Object.throwErr (http://localhost:52498/__cypress/runner/cypress_runner.js:65692:18)\n    at Object.throwErrByPath (http://localhost:52498/__cypress/runner/cypress_runner.js:65719:17)\n    at http://localhost:52498/__cypress/runner/cypress_runner.js:57021:23\n    at tryCatcher (http://localhost:52498/__cypress/runner/cypress_runner.js:131273:23)\n    at http://localhost:52498/__cypress/runner/cypress_runner.js:126600:37\n    at tryCatcher (http://localhost:52498/__cypress/runner/cypress_runner.js:131273:23)\n    at Promise._settlePromiseFromHandler (http://localhost:52498/__cypress/runner/cypress_runner.js:129291:31)\n    at Promise._settlePromise (http://localhost:52498/__cypress/runner/cypress_runner.js:129348:18)\n    at Promise._settlePromise0 (http://localhost:52498/__cypress/runner/cypress_runner.js:129393:10)\n    at Promise._settlePromises (http://localhost:52498/__cypress/runner/cypress_runner.js:129468:18)\n    at Async._drainQueue (http://localhost:52498/__cypress/runner/cypress_runner.js:126197:16)\n    at Async._drainQueues (http://localhost:52498/__cypress/runner/cypress_runner.js:126207:10)\n    at Async.drainQueues (http://localhost:52498/__cypress/runner/cypress_runner.js:126081:14)\n    at &lt;anonymous&gt;&quot;,&quot;diff&quot;:null},&quot;uuid&quot;:&quot;ca5f41f7-84a4-4978-87a8-41d1537e710d&quot;,&quot;parentUUID&quot;:&quot;b503848c-31a5-4415-b5ce-83f0d4f61ba2&quot;,&quot;isHook&quot;:false,&quot;skipped&quot;:false},{&quot;title&quot;:&quot;Validate the status&quot;,&quot;fullTitle&quot;:&quot;API Testing with Cypress Validate the status&quot;,&quot;timedOut&quot;:null,&quot;duration&quot;:366,&quot;state&quot;:&quot;failed&quot;,&quot;speed&quot;:null,&quot;pass&quot;:false,&quot;fail&quot;:true,&quot;pending&quot;:false,&quot;context&quot;:null,&quot;code&quot;:&quot;result = cy.request(&#x27;http://services.groupkt.com/country/get/iso2code/AU&#x27;);\nresult.its(&#x27;status&#x27;).should(&#x27;equal&#x27;, 200);&quot;,&quot;err&quot;:{&quot;message&quot;:&quot;CypressError: cy.request() failed trying to load:\n\nhttp://services.groupkt.com/country/get/iso2code/AU\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: getaddrinfo ENOTFOUND services.groupkt.com services.groupkt.com:80\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: http://services.groupkt.com/country/get/iso2code/AU\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: getaddrinfo ENOTFOUND services.groupkt.com services.groupkt.com:80\n    at new RequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:185:22)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at Request.onRequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:881:8)\n    at emitOne (events.js:120:20)\n    at ClientRequest.emit (events.js:210:7)\n    at Socket.socketErrorListener (_http_client.js:401:9)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n&quot;,&quot;estack&quot;:&quot;CypressError: cy.request() failed trying to load:\n\nhttp://services.groupkt.com/country/get/iso2code/AU\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: getaddrinfo ENOTFOUND services.groupkt.com services.groupkt.com:80\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: http://services.groupkt.com/country/get/iso2code/AU\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: getaddrinfo ENOTFOUND services.groupkt.com services.groupkt.com:80\n    at new RequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:185:22)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at Request.onRequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:881:8)\n    at emitOne (events.js:120:20)\n    at ClientRequest.emit (events.js:210:7)\n    at Socket.socketErrorListener (_http_client.js:401:9)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n\n    at Object.cypressErr (http://localhost:52498/__cypress/runner/cypress_runner.js:65727:11)\n    at Object.throwErr (http://localhost:52498/__cypress/runner/cypress_runner.js:65692:18)\n    at Object.throwErrByPath (http://localhost:52498/__cypress/runner/cypress_runner.js:65719:17)\n    at http://localhost:52498/__cypress/runner/cypress_runner.js:57021:23\n    at tryCatcher (http://localhost:52498/__cypress/runner/cypress_runner.js:131273:23)\n    at http://localhost:52498/__cypress/runner/cypress_runner.js:126600:37\n    at tryCatcher (http://localhost:52498/__cypress/runner/cypress_runner.js:131273:23)\n    at Promise._settlePromiseFromHandler (http://localhost:52498/__cypress/runner/cypress_runner.js:129291:31)\n    at Promise._settlePromise (http://localhost:52498/__cypress/runner/cypress_runner.js:129348:18)\n    at Promise._settlePromise0 (http://localhost:52498/__cypress/runner/cypress_runner.js:129393:10)\n    at Promise._settlePromises (http://localhost:52498/__cypress/runner/cypress_runner.js:129468:18)\n    at Async._drainQueue (http://localhost:52498/__cypress/runner/cypress_runner.js:126197:16)\n    at Async._drainQueues (http://localhost:52498/__cypress/runner/cypress_runner.js:126207:10)\n    at Async.drainQueues (http://localhost:52498/__cypress/runner/cypress_runner.js:126081:14)\n    at &lt;anonymous&gt;&quot;,&quot;diff&quot;:null},&quot;uuid&quot;:&quot;427154c5-86b0-4909-bb5b-b38e08a06c65&quot;,&quot;parentUUID&quot;:&quot;b503848c-31a5-4415-b5ce-83f0d4f61ba2&quot;,&quot;isHook&quot;:false,&quot;skipped&quot;:false},{&quot;title&quot;:&quot;Validate the body &quot;,&quot;fullTitle&quot;:&quot;API Testing with Cypress Validate the body &quot;,&quot;timedOut&quot;:null,&quot;duration&quot;:331,&quot;state&quot;:&quot;failed&quot;,&quot;speed&quot;:null,&quot;pass&quot;:false,&quot;fail&quot;:true,&quot;pending&quot;:false,&quot;context&quot;:null,&quot;code&quot;:&quot;result = cy.request(&#x27;http://services.groupkt.com/country/get/iso2code/AU&#x27;);\nresult.its(&#x27;body&#x27;).its(&#x27;RestResponse.messages&#x27;).should(&#x27;include&#x27;, &#x27;Country found matching code [AU].&#x27;);&quot;,&quot;err&quot;:{&quot;message&quot;:&quot;CypressError: cy.request() failed trying to load:\n\nhttp://services.groupkt.com/country/get/iso2code/AU\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: getaddrinfo ENOTFOUND services.groupkt.com services.groupkt.com:80\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: http://services.groupkt.com/country/get/iso2code/AU\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: getaddrinfo ENOTFOUND services.groupkt.com services.groupkt.com:80\n    at new RequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:185:22)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at Request.onRequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:881:8)\n    at emitOne (events.js:120:20)\n    at ClientRequest.emit (events.js:210:7)\n    at Socket.socketErrorListener (_http_client.js:401:9)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n&quot;,&quot;estack&quot;:&quot;CypressError: cy.request() failed trying to load:\n\nhttp://services.groupkt.com/country/get/iso2code/AU\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: getaddrinfo ENOTFOUND services.groupkt.com services.groupkt.com:80\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: http://services.groupkt.com/country/get/iso2code/AU\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: getaddrinfo ENOTFOUND services.groupkt.com services.groupkt.com:80\n    at new RequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:185:22)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at Request.onRequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:881:8)\n    at emitOne (events.js:120:20)\n    at ClientRequest.emit (events.js:210:7)\n    at Socket.socketErrorListener (_http_client.js:401:9)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n\n    at Object.cypressErr (http://localhost:52498/__cypress/runner/cypress_runner.js:65727:11)\n    at Object.throwErr (http://localhost:52498/__cypress/runner/cypress_runner.js:65692:18)\n    at Object.throwErrByPath (http://localhost:52498/__cypress/runner/cypress_runner.js:65719:17)\n    at http://localhost:52498/__cypress/runner/cypress_runner.js:57021:23\n    at tryCatcher (http://localhost:52498/__cypress/runner/cypress_runner.js:131273:23)\n    at http://localhost:52498/__cypress/runner/cypress_runner.js:126600:37\n    at tryCatcher (http://localhost:52498/__cypress/runner/cypress_runner.js:131273:23)\n    at Promise._settlePromiseFromHandler (http://localhost:52498/__cypress/runner/cypress_runner.js:129291:31)\n    at Promise._settlePromise (http://localhost:52498/__cypress/runner/cypress_runner.js:129348:18)\n    at Promise._settlePromise0 (http://localhost:52498/__cypress/runner/cypress_runner.js:129393:10)\n    at Promise._settlePromises (http://localhost:52498/__cypress/runner/cypress_runner.js:129468:18)\n    at Async._drainQueue (http://localhost:52498/__cypress/runner/cypress_runner.js:126197:16)\n    at Async._drainQueues (http://localhost:52498/__cypress/runner/cypress_runner.js:126207:10)\n    at Async.drainQueues (http://localhost:52498/__cypress/runner/cypress_runner.js:126081:14)\n    at &lt;anonymous&gt;&quot;,&quot;diff&quot;:null},&quot;uuid&quot;:&quot;f7025806-a636-4128-9165-2fb37cd39b94&quot;,&quot;parentUUID&quot;:&quot;b503848c-31a5-4415-b5ce-83f0d4f61ba2&quot;,&quot;isHook&quot;:false,&quot;skipped&quot;:false}],&quot;suites&quot;:[],&quot;passes&quot;:[],&quot;failures&quot;:[&quot;ca5f41f7-84a4-4978-87a8-41d1537e710d&quot;,&quot;427154c5-86b0-4909-bb5b-b38e08a06c65&quot;,&quot;f7025806-a636-4128-9165-2fb37cd39b94&quot;],&quot;pending&quot;:[],&quot;skipped&quot;:[],&quot;duration&quot;:1463,&quot;root&quot;:false,&quot;rootEmpty&quot;:false,&quot;_timeout&quot;:2000}],&quot;passes&quot;:[],&quot;failures&quot;:[],&quot;pending&quot;:[],&quot;skipped&quot;:[],&quot;duration&quot;:0,&quot;root&quot;:true,&quot;rootEmpty&quot;:true,&quot;_timeout&quot;:2000},{&quot;uuid&quot;:&quot;ee158f72-bf3e-477a-829b-9cc98d504ef9&quot;,&quot;title&quot;:&quot;&quot;,&quot;fullFile&quot;:&quot;&quot;,&quot;file&quot;:&quot;&quot;,&quot;beforeHooks&quot;:[],&quot;afterHooks&quot;:[],&quot;tests&quot;:[],&quot;suites&quot;:[{&quot;uuid&quot;:&quot;202a2fbb-f4c9-436e-a4de-94dae7e77c0e&quot;,&quot;title&quot;:&quot;Test API from the Fake JSON serer&quot;,&quot;fullFile&quot;:&quot;&quot;,&quot;file&quot;:&quot;&quot;,&quot;beforeHooks&quot;:[],&quot;afterHooks&quot;:[],&quot;tests&quot;:[{&quot;title&quot;:&quot;Test GET functionality of JSON server&quot;,&quot;fullTitle&quot;:&quot;Test API from the Fake JSON serer Test GET functionality of JSON server&quot;,&quot;timedOut&quot;:null,&quot;duration&quot;:453,&quot;state&quot;:&quot;failed&quot;,&quot;speed&quot;:null,&quot;pass&quot;:false,&quot;fail&quot;:true,&quot;pending&quot;:false,&quot;context&quot;:null,&quot;code&quot;:&quot;cy.request(\&quot;http://localhost:3000/posts/1\&quot;).its(\&quot;body\&quot;).should(\&quot;have.property\&quot;, \&quot;id\&quot;);&quot;,&quot;err&quot;:{&quot;message&quot;:&quot;CypressError: cy.request() failed trying to load:\n\nhttp://localhost:3000/posts/1\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: connect ECONNREFUSED 127.0.0.1:3000\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: http://localhost:3000/posts/1\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: connect ECONNREFUSED 127.0.0.1:3000\n    at new RequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:185:22)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at Request.onRequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:881:8)\n    at emitOne (events.js:120:20)\n    at ClientRequest.emit (events.js:210:7)\n    at Socket.socketErrorListener (_http_client.js:401:9)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n&quot;,&quot;estack&quot;:&quot;CypressError: cy.request() failed trying to load:\n\nhttp://localhost:3000/posts/1\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: connect ECONNREFUSED 127.0.0.1:3000\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: http://localhost:3000/posts/1\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: connect ECONNREFUSED 127.0.0.1:3000\n    at new RequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:185:22)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at Request.onRequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:881:8)\n    at emitOne (events.js:120:20)\n    at ClientRequest.emit (events.js:210:7)\n    at Socket.socketErrorListener (_http_client.js:401:9)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n\n    at Object.cypressErr (http://localhost:52498/__cypress/runner/cypress_runner.js:65727:11)\n    at Object.throwErr (http://localhost:52498/__cypress/runner/cypress_runner.js:65692:18)\n    at Object.throwErrByPath (http://localhost:52498/__cypress/runner/cypress_runner.js:65719:17)\n    at http://localhost:52498/__cypress/runner/cypress_runner.js:57021:23\n    at tryCatcher (http://localhost:52498/__cypress/runner/cypress_runner.js:131273:23)\n    at http://localhost:52498/__cypress/runner/cypress_runner.js:126600:37\n    at tryCatcher (http://localhost:52498/__cypress/runner/cypress_runner.js:131273:23)\n    at Promise._settlePromiseFromHandler (http://localhost:52498/__cypress/runner/cypress_runner.js:129291:31)\n    at Promise._settlePromise (http://localhost:52498/__cypress/runner/cypress_runner.js:129348:18)\n    at Promise._settlePromise0 (http://localhost:52498/__cypress/runner/cypress_runner.js:129393:10)\n    at Promise._settlePromises (http://localhost:52498/__cypress/runner/cypress_runner.js:129468:18)\n    at Async._drainQueue (http://localhost:52498/__cypress/runner/cypress_runner.js:126197:16)\n    at Async._drainQueues (http://localhost:52498/__cypress/runner/cypress_runner.js:126207:10)\n    at Async.drainQueues (http://localhost:52498/__cypress/runner/cypress_runner.js:126081:14)\n    at &lt;anonymous&gt;&quot;,&quot;diff&quot;:null},&quot;uuid&quot;:&quot;93b6c651-7a4e-44ef-95b5-8c815cd76d4d&quot;,&quot;parentUUID&quot;:&quot;202a2fbb-f4c9-436e-a4de-94dae7e77c0e&quot;,&quot;isHook&quot;:false,&quot;skipped&quot;:false},{&quot;title&quot;:&quot;Test POST functionality of JSON Server&quot;,&quot;fullTitle&quot;:&quot;Test API from the Fake JSON serer Test POST functionality of JSON Server&quot;,&quot;timedOut&quot;:null,&quot;duration&quot;:254,&quot;state&quot;:&quot;failed&quot;,&quot;speed&quot;:null,&quot;pass&quot;:false,&quot;fail&quot;:true,&quot;pending&quot;:false,&quot;context&quot;:null,&quot;code&quot;:&quot;var idInput = Math.floor(length + Math.random() * length * 9);\ncy.request({\n  method: \&quot;POST\&quot;,\n  url: \&quot;http://localhost:3000/posts\&quot;,\n  body: {\n    id: idInput,\n    title: \&quot;Automation\&quot;,\n    author: \&quot;billy\&quot;\n  }\n}).then(function (res) {\n  expect(res.body).has.property(\&quot;title\&quot;, \&quot;Automation\&quot;);\n});&quot;,&quot;err&quot;:{&quot;message&quot;:&quot;CypressError: cy.request() failed trying to load:\n\nhttp://localhost:3000/posts\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: connect ECONNREFUSED 127.0.0.1:3000\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: POST\nURL: http://localhost:3000/posts\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: connect ECONNREFUSED 127.0.0.1:3000\n    at new RequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:185:22)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at Request.onRequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:881:8)\n    at emitOne (events.js:120:20)\n    at ClientRequest.emit (events.js:210:7)\n    at Socket.socketErrorListener (_http_client.js:401:9)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n&quot;,&quot;estack&quot;:&quot;CypressError: cy.request() failed trying to load:\n\nhttp://localhost:3000/posts\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: connect ECONNREFUSED 127.0.0.1:3000\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: POST\nURL: http://localhost:3000/posts\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: connect ECONNREFUSED 127.0.0.1:3000\n    at new RequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:185:22)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at Request.onRequestError (/Users/pro/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:881:8)\n    at emitOne (events.js:120:20)\n    at ClientRequest.emit (events.js:210:7)\n    at Socket.socketErrorListener (_http_client.js:401:9)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n\n    at Object.cypressErr (http://localhost:52498/__cypress/runner/cypress_runner.js:65727:11)\n    at Object.throwErr (http://localhost:52498/__cypress/runner/cypress_runner.js:65692:18)\n    at Object.throwErrByPath (http://localhost:52498/__cypress/runner/cypress_runner.js:65719:17)\n    at http://localhost:52498/__cypress/runner/cypress_runner.js:57021:23\n    at tryCatcher (http://localhost:52498/__cypress/runner/cypress_runner.js:131273:23)\n    at http://localhost:52498/__cypress/runner/cypress_runner.js:126600:37\n    at tryCatcher (http://localhost:52498/__cypress/runner/cypress_runner.js:131273:23)\n    at Promise._settlePromiseFromHandler (http://localhost:52498/__cypress/runner/cypress_runner.js:129291:31)\n    at Promise._settlePromise (http://localhost:52498/__cypress/runner/cypress_runner.js:129348:18)\n    at Promise._settlePromise0 (http://localhost:52498/__cypress/runner/cypress_runner.js:129393:10)\n    at Promise._settlePromises (http://localhost:52498/__cypress/runner/cypress_runner.js:129468:18)\n    at Async._drainQueue (http://localhost:52498/__cypress/runner/cypress_runner.js:126197:16)\n    at Async._drainQueues (http://localhost:52498/__cypress/runner/cypress_runner.js:126207:10)\n    at Async.drainQueues (http://localhost:52498/__cypress/runner/cypress_runner.js:126081:14)\n    at &lt;anonymous&gt;&quot;,&quot;diff&quot;:null},&quot;uuid&quot;:&quot;a63433c4-e706-4404-8520-a6b2cd8eb2fa&quot;,&quot;parentUUID&quot;:&quot;202a2fbb-f4c9-436e-a4de-94dae7e77c0e&quot;,&quot;isHook&quot;:false,&quot;skipped&quot;:false},{&quot;title&quot;:&quot;API testing&quot;,&quot;fullTitle&quot;:&quot;Test API from the Fake JSON serer API testing&quot;,&quot;timedOut&quot;:null,&quot;duration&quot;:298,&quot;state&quot;:&quot;passed&quot;,&quot;speed&quot;:&quot;slow&quot;,&quot;pass&quot;:true,&quot;fail&quot;:false,&quot;pending&quot;:false,&quot;context&quot;:null,&quot;code&quot;:&quot;cy.request({\n  method: \&quot;POST\&quot;,\n  url: \&quot;http://eaapp.somee.com/Account/Login\&quot;,\n  body: {\n    __RequestVerificationToken: \&quot;jJ27CGSB6SHC24F0oV5nGIcKmDPqG2WfwOCDZxTUIhJ8Tk9TiSYlzhrzuhP5Ct2rHTiOY46WawRVGy6qanY18HsdbKEeK0TqWjgOY9b6RZE1\&quot;,\n    UserName: \&quot;admin\&quot;,\n    Password: \&quot;password\&quot;,\n    RememberMe: \&quot;false\&quot;\n  },\n  failOnStatusCode: false\n}).then(function ($res) {\n  expect($res.status).to.eql(500);\n  expect($res.body).to.contain(\&quot;&lt;i&gt;The required anti-forgery cookie &amp;quot;__RequestVerificationToken&amp;quot; is not present.&lt;/i&gt;\&quot;);\n});&quot;,&quot;err&quot;:{},&quot;uuid&quot;:&quot;0d552834-e369-448c-a189-8f0f4c53c644&quot;,&quot;parentUUID&quot;:&quot;202a2fbb-f4c9-436e-a4de-94dae7e77c0e&quot;,&quot;isHook&quot;:false,&quot;skipped&quot;:false}],&quot;suites&quot;:[],&quot;passes&quot;:[&quot;0d552834-e369-448c-a189-8f0f4c53c644&quot;],&quot;failures&quot;:[&quot;93b6c651-7a4e-44ef-95b5-8c815cd76d4d&quot;,&quot;a63433c4-e706-4404-8520-a6b2cd8eb2fa&quot;],&quot;pending&quot;:[],&quot;skipped&quot;:[],&quot;duration&quot;:1005,&quot;root&quot;:false,&quot;rootEmpty&quot;:false,&quot;_timeout&quot;:2000}],&quot;passes&quot;:[],&quot;failures&quot;:[],&quot;pending&quot;:[],&quot;skipped&quot;:[],&quot;duration&quot;:0,&quot;root&quot;:true,&quot;rootEmpty&quot;:true,&quot;_timeout&quot;:2000}],&quot;meta&quot;:{&quot;mocha&quot;:{&quot;version&quot;:&quot;6.2.3&quot;},&quot;mochawesome&quot;:{&quot;options&quot;:{&quot;quiet&quot;:true,&quot;reportFilename&quot;:&quot;mochawesome&quot;,&quot;saveHtml&quot;:false,&quot;saveJson&quot;:true,&quot;consoleReporter&quot;:&quot;spec&quot;,&quot;useInlineDiffs&quot;:false},&quot;version&quot;:&quot;4.1.0&quot;},&quot;marge&quot;:{&quot;options&quot;:{&quot;id&quot;:&quot;default&quot;,&quot;reportDir&quot;:&quot;mochawesome-report&quot;,&quot;quiet&quot;:true,&quot;overwrite&quot;:false,&quot;html&quot;:false,&quot;json&quot;:true},&quot;version&quot;:&quot;4.1.0&quot;}}}" data-config="{&quot;reportFilename&quot;:&quot;report&quot;,&quot;reportDir&quot;:&quot;mochareports&quot;,&quot;reportTitle&quot;:&quot;CypressExample&quot;,&quot;reportPageTitle&quot;:&quot;Mochawesome Report&quot;,&quot;inline&quot;:false,&quot;inlineAssets&quot;:false,&quot;cdn&quot;:false,&quot;charts&quot;:false,&quot;enableCharts&quot;:false,&quot;code&quot;:true,&quot;enableCode&quot;:true,&quot;autoOpen&quot;:false,&quot;overwrite&quot;:true,&quot;timestamp&quot;:false,&quot;ts&quot;:false,&quot;showPassed&quot;:true,&quot;showFailed&quot;:true,&quot;showPending&quot;:true,&quot;showSkipped&quot;:false,&quot;showHooks&quot;:&quot;failed&quot;,&quot;saveJson&quot;:false,&quot;saveHtml&quot;:true,&quot;dev&quot;:false,&quot;assetsDir&quot;:&quot;mochareports/assets&quot;,&quot;htmlFile&quot;:&quot;/Users/Billy/GitHub/CypressExample/mochareports/report.html&quot;}"><div id="report"></div><script src="assets/app.js"></script></body></html>